# Unique project identifier in SonarQube
sonar.projectKey=pci-ssf-node-service
sonar.projectName=PCI SSF Node.js Service
sonar.projectVersion=1.0.0

# Path to source code (usually 'src' or '.' for root)
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.spec.js, **/*.test.js

# Encoding
sonar.sourceEncoding=UTF-8
# Forget local .git - [ can't reach because our .git is a worktree]
sonar.scm.disabled=true